### ISSUE TITLE
scroll down twitch page doesnt work 

### ISSUE THREAD

**Issue by matheustanaka** [mbalabash/puppeteer-autoscroll-down#14]
I'm trying to scroll down https://www.twitch.tv/ 
But for some reason it doesn't  work, i don't know what's happening.
When I use autoscroll with other pages, it works.

Any suggestion of how can i solve that?

**Comment by mbalabash** [comment]
With the current implementation, it is impossible to solve, because on that website they use a custom scroll so scrolling the body element is not an option. To support this case we need to add a new optional parameter to a scrolling function with a custom selector for a scrolling container. 

I would be happy to add support for this case, so you can create a PR with required change.
